[2025-02-23T11:12:44.917+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-23T11:12:44.940+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: open_tax_etl.transform_task manual__2025-02-23T11:12:42.745847+00:00 [queued]>
[2025-02-23T11:12:44.945+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: open_tax_etl.transform_task manual__2025-02-23T11:12:42.745847+00:00 [queued]>
[2025-02-23T11:12:44.946+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-23T11:12:44.955+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_task> on 2025-02-23 11:12:42.745847+00:00
[2025-02-23T11:12:44.961+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'open_tax_etl', 'transform_task', 'manual__2025-02-23T11:12:42.745847+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/opentaxetl.py', '--cfg-path', '/tmp/tmp7co537mp']
[2025-02-23T11:12:44.966+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1549) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T11:12:44.966+0000] {standard_task_runner.py:91} INFO - Job 43: Subtask transform_task
[2025-02-23T11:12:44.966+0000] {standard_task_runner.py:64} INFO - Started process 1551 to run task
[2025-02-23T11:12:44.993+0000] {task_command.py:426} INFO - Running <TaskInstance: open_tax_etl.transform_task manual__2025-02-23T11:12:42.745847+00:00 [running]> on host 2cf524a0af0b
[2025-02-23T11:12:45.145+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='open_tax_etl' AIRFLOW_CTX_TASK_ID='transform_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-23T11:12:42.745847+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-23T11:12:42.745847+00:00'
[2025-02-23T11:12:45.146+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-23T11:12:45.167+0000] {logging_mixin.py:188} INFO - Columns in DataFrame: Index(['transaction_id', 'user_id', 'amount', 'transaction_date'], dtype='object')
[2025-02-23T11:12:45.168+0000] {logging_mixin.py:188} INFO - First few rows of DataFrame:
[2025-02-23T11:12:45.176+0000] {logging_mixin.py:188} INFO -    transaction_id  user_id    amount transaction_date
0      TXN204793     1408       0.0       2024-11-07
1      TXN749110     1716       NaN       2024-06-28
2      TXN984574     1934       NaN       2024-09-15
3      TXN180036     1034  -3437.55       10/11/2024
4      TXN147245     1497       0.0       09/12/2024
[2025-02-23T11:12:45.179+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-23T11:12:45.179+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/opentaxetl.py", line 43, in transform_data
    dataframe['amount'] = dataframe['amount'].astype(float)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/dtypes/astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/dtypes/astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/dtypes/astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '$4990.00'
[2025-02-23T11:12:45.193+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=open_tax_etl, task_id=transform_task, run_id=manual__2025-02-23T11:12:42.745847+00:00, execution_date=20250223T111242, start_date=20250223T111244, end_date=20250223T111245
[2025-02-23T11:12:45.199+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 43 for task transform_task (could not convert string to float: '$4990.00'; 1551)
[2025-02-23T11:12:45.241+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-02-23T11:12:45.252+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-23T11:12:45.253+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
