[2025-02-23T10:57:57.312+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-23T10:57:57.339+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: open_tax_etl.transform_task manual__2025-02-23T10:57:56.061503+00:00 [queued]>
[2025-02-23T10:57:57.347+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: open_tax_etl.transform_task manual__2025-02-23T10:57:56.061503+00:00 [queued]>
[2025-02-23T10:57:57.347+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-23T10:57:57.357+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_task> on 2025-02-23 10:57:56.061503+00:00
[2025-02-23T10:57:57.368+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'open_tax_etl', 'transform_task', 'manual__2025-02-23T10:57:56.061503+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/opentaxetl.py', '--cfg-path', '/tmp/tmpmg281x6z']
[2025-02-23T10:57:57.370+0000] {standard_task_runner.py:91} INFO - Job 27: Subtask transform_task
[2025-02-23T10:57:57.371+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1144) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T10:57:57.372+0000] {standard_task_runner.py:64} INFO - Started process 1149 to run task
[2025-02-23T10:57:57.408+0000] {task_command.py:426} INFO - Running <TaskInstance: open_tax_etl.transform_task manual__2025-02-23T10:57:56.061503+00:00 [running]> on host 2cf524a0af0b
[2025-02-23T10:57:57.696+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='open_tax_etl' AIRFLOW_CTX_TASK_ID='transform_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-23T10:57:56.061503+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-23T10:57:56.061503+00:00'
[2025-02-23T10:57:57.697+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-23T10:57:57.715+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-23T10:57:57.715+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/opentaxetl.py", line 37, in transform_data
    dataframe['amount'] = dataframe['amount'].str.replace('$', '', regex=True).astype(float)
                          ~~~~~~~~~^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3893, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/range.py", line 418, in get_loc
    raise KeyError(key)
KeyError: 'amount'
[2025-02-23T10:57:57.729+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=open_tax_etl, task_id=transform_task, run_id=manual__2025-02-23T10:57:56.061503+00:00, execution_date=20250223T105756, start_date=20250223T105757, end_date=20250223T105757
[2025-02-23T10:57:57.742+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 27 for task transform_task ('amount'; 1149)
[2025-02-23T10:57:57.758+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-02-23T10:57:57.777+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-23T10:57:57.778+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
